### ISSUE TITLE
missing includes.h

### ISSUE THREAD

**Issue by youone** [berickson1/DE2-Ethernet#1]
I'm trying to port this to a DE2-70 board and Quartus 13.0, but when compiling it is complaining over a missing includes.h file.

**Comment by berickson1** [comment]
Can you include the relevant compiler output?

**Comment by youone** [comment]
Here it is. This happens when I create a new project from the sopcinfo generated in Qartus, and then copy the source files from DE2-Ethernet\Software\EthernetExample into that project:

***\* Build of configuration Nios II for project proj_de2ethernet ****

make all 
Info: Building ../proj_de2ethernet_bsp/
make --no-print-directory -C ../proj_de2ethernet_bsp/
[BSP build complete]
Info: Compiling alt_error_handler.c to obj/default/alt_error_handler.o
nios2-elf-gcc -xc -MP -MMD -c -I../proj_de2ethernet_bsp//HAL/inc -I../proj_de2ethernet_bsp/ -I../proj_de2ethernet_bsp//drivers/inc  -DSYSTEM_BUS_WIDTH=32 -pipe -D__hal__ -DALT_NO_INSTRUCTION_EMULATION -DALT_SINGLE_THREADED    -O0 -g -Wall   -EL -mno-hw-div -mno-hw-mul -mno-hw-mulx  -o obj/default/alt_error_handler.o alt_error_handler.c
In file included from alt_error_handler.c:98:
alt_error_handler.h:67:22: error: includes.h: No such file or directory
In file included from alt_error_handler.c:98:
alt_error_handler.h:79: error: expected ')' before 'error_code'
alt_error_handler.c:100: error: expected ')' before 'error_code'
make: **\* [obj/default/alt_error_handler.o] Error 1

***\* Build Finished ****

I also tried importing the whole project into Eclipse, but then I get:

***\* Build of configuration Nios II for project EthernetExample ****

make all 
makefile:238: **\* BSP directory does not exist: H:/De2-115/DE2-Ethernet/Software/EthernetExample_bsp/.  Stop.

***\* Build Finished ****

**Comment by berickson1** [comment]
includes.h is the default MicroC/OS-II include file.  It should be auto-generated in the bsp project (Project_bsp/HAL/inc/includes.h).  Are you sure that you've properly created the bsp project? Try re-creating it.

I haven't dusted off this project in quite a while but if you're still having issues I may be able to get quartus back up and running on my system and try it myself

**Comment by youone** [comment]
Ok, thanks! Seems like I have to read a bit about MicroC/OS-II. Found this: 

https://www.altera.com/content/dam/altera-www/global/en_US/pdfs/literature/tt/tt_nios2_microc_osii_tutorial.pdf

It will probably put me on the right track.

**Comment by berickson1** [comment]
@youone Any luck?
